# Generated by Django 4.1.2 on 2023-10-08 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_film_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='duration',
        ),
    ]
