# Generated by Django 4.1.2 on 2023-10-08 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_film_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='short_description',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
